### PR TITLE
Create zh_cn.json file

### PR DESCRIPTION
**Pull request by 1235788998753568hfjfu**
Hello again, here is the Chinese translation made by @Rivmun Candlelight Dinner (and I modified it a bit), lang file if it is not finished, can you finish it? When you're done, I'll finish the rest of it! Thank you :)

### CODE REVIEW

**Comment by Rivmun** [comment]
你这文件路径怎么多了一堆空格啊……这不可能给你合并的啊……

**Comment by lk007-qi** [comment]
妈呀，坏了我去改一下

**Comment by satisfyu** [comment]
Were not done yet. :D Still some stuff to come!

**Comment by lk007-qi** [comment]
OK, I'll be waiting for it to arrive!

**Pull request merged**
